CREATE ROLE experiments LOGIN;
CREATE DATABASE experiments OWNER experiments;
REVOKE CONNECT, TEMPORARY ON DATABASE postgres FROM PUBLIC;
REVOKE CONNECT, TEMPORARY ON DATABASE template1 FROM PUBLIC;
REVOKE CONNECT, TEMPORARY ON DATABASE experiments FROM PUBLIC;
ALTER ROLE experiments PASSWORD :hash;
