build-and-deploy:
  image: quay.io/podman/stable:latest
  tags: [saas-linux-small-amd64]
  script:
    - bash build-and-deploy.sh
  rules:
    - changes:
        - "**/*"
        - "!README.md"
        - "!provision.sh"
