[Unit]
Requires=post-startup-root.service
After=post-startup-root.service

[Service]
ProtectSystem=strict
ProtectHome=true
ProtectProc=invisible
ProtectClock=true
ProtectKernelLogs=true
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectHostname=true
PrivateDevices=true
PrivateTmp=true
PrivateIPC=true
RestrictNamespaces=true
NoNewPrivileges=true
LockPersonality=true
MemoryDenyWriteExecute=true
RestrictSUIDSGID=true
RestrictRealtime=true
RestrictAddressFamilies=AF_UNIX AF_INET
SystemCallFilter=@system-service
SystemCallArchitectures=native
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
ReadWritePaths=/var/lib/caddy
UMask=0077
