# ----------------------------------------
# experiments DB: only allowed DB
# ----------------------------------------
local   experiments     all                                 trust
host    experiments     all             127.0.0.1/32        trust
host    experiments     all             ::1/128             trust

# ----------------------------------------
# postgres DB: fully disabled
# ----------------------------------------
local   postgres        all                                 reject
host    postgres        all             127.0.0.1/32        reject
host    postgres        all             ::1/128             reject

# ----------------------------------------
# deny everything else
# ----------------------------------------
host    all             all             0.0.0.0/0           reject
host    all             all             ::0/0               reject
