# ----------------------------------------
# experiments DB: only allowed DB
# ----------------------------------------
local   experiments     all                                 trust
host    experiments     all             10.89.0.0/24        trust

# ----------------------------------------
# deny everything else
# ----------------------------------------
local   all             all                                 reject
host    all             all             all                 reject
