[Unit]
Requires=post-startup.service
After=post-startup.service

[Service]
ProtectSystem=strict
ProtectHome=true
ProtectProc=invisible
PrivateDevices=true
PrivateTmp=true
NoNewPrivileges=true
LockPersonality=true
MemoryDenyWriteExecute=true
RestrictSUIDSGID=true
RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6
SystemCallFilter=@system-service
SystemCallArchitectures=native
CapabilityBoundingSet=
ReadWritePaths=/var/lib/pgsql /run/postgresql
