#!/usr/bin/env bash
set -euo pipefail

# ----------------------------
# Packages
# ----------------------------
dnf install -y caddy httpd postgresql17-server
dnf clean all


# ----------------------------
# Rebuild initramfs so prepare-root.conf's [etc] transient takes effect.
# /root is a symlink to /var/roothome; materialize it for dracut-install,
# then remove so the image's /var stays empty.
# ----------------------------
KVER=$(basename /usr/lib/modules/*)
mkdir -p /var/roothome
dracut --no-hostonly --force --kver "$KVER" /usr/lib/modules/"$KVER"/initramfs.img
rmdir /var/roothome


# ----------------------------
# SSH host keys live in /var/lib/sshd (generated by post-startup.sh on
# first boot). Symlinks at /etc/ssh point there so sshd uses default
# config paths. sshd-keygen@<type>.service is a no-op once the symlink
# targets are populated (ConditionFileNotEmpty=|! returns false).
# ----------------------------
for t in rsa ecdsa ed25519; do
    ln -s "/var/lib/sshd/ssh_host_${t}_key"     "/etc/ssh/ssh_host_${t}_key"
    ln -s "/var/lib/sshd/ssh_host_${t}_key.pub" "/etc/ssh/ssh_host_${t}_key.pub"
done


# ----------------------------
# Users: experiments is ssh-forward-only into postgres
# ----------------------------
mkdir -p /usr/share/experiments
useradd -M -d /usr/share/experiments -s /usr/sbin/nologin experiments


# ----------------------------
# httpd: drop the default Listen 80 so webdav.conf can own the bind
# ----------------------------
sed -i '/^Listen /d' /etc/httpd/conf/httpd.conf


# ----------------------------
# Services
# ----------------------------
systemctl enable post-startup.service \
                 caddy.service \
                 httpd.service \
                 postgresql.service \
                 bootc-fetch-apply-updates.timer

chmod +x /usr/libexec/post-startup.sh
