Listen 127.0.0.1:8080
DavLockDB /var/lib/webdav/lock/lockdb

<VirtualHost *:8080>
    DocumentRoot "/var/lib/webdav/data"

    <Directory "/var/lib/webdav/data">
        Dav On
        Options Indexes
        Require all granted
    </Directory>
</VirtualHost>
