name: build-and-deploy

on:
  workflow_dispatch:
  push:
    branches: [main]

concurrency:
  group: build-and-deploy
  cancel-in-progress: false

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v7

      - name: Build and deploy
        run: sudo -E PATH="$PATH" bash build-and-deploy.sh
        env:
          CI_REGISTRY: ghcr.io
          CI_REGISTRY_IMAGE: ghcr.io/${{ github.repository }}
          CI_REGISTRY_USER: ${{ github.actor }}
          CI_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          CLOUDSDK_CORE_PROJECT: ${{ secrets.CLOUDSDK_CORE_PROJECT }}
